// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujrildvleyzrtwfmoxbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqcmlsZHZsZXl6cnR3Zm1veGJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0OTkxMjQsImV4cCI6MjA2NTA3NTEyNH0.S3F3bfJxNoMvOdDRIYWeh3aLu8vLirpcIgSYa40Qif8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);